# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_macosx
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

INCLUDES += -I../../src -I../../src/osdep -I/opt/homebrew/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LDDEPS +=
LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_macosx)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = ../../build/bin
TARGET = $(TARGETDIR)/libgoahead.dylib
OBJDIR = ../../build/obj/goahead-lib-macosx-debug
DEFINES += -DME_VERSION=\"6.1.1\" -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_SSL=1 -DME_COM_OPENSSL_PATH=\"/opt/homebrew\" -DME_COM_MBEDTLS_PATH=\"/usr\" -DME_DEBUG=1
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -fPIC -g -Wall -Wextra -std=gnu11 -Wno-sign-conversion -Wno-unused-parameter -Wno-unused-result -Wshorten-64-to-32 -Wall -Wno-unknown-warning-option -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -fPIC -g -Wall -Wextra -Wno-sign-conversion -Wno-unused-parameter -Wno-unused-result -Wshorten-64-to-32 -Wall -Wno-unknown-warning-option -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
LIBS += -ldl -lpthread -lm -lpam -lssl -lcrypto
ALL_LDFLAGS += $(LDFLAGS) -L/opt/homebrew/lib -dynamiclib -Wl,-install_name,@rpath/libgoahead.dylib -g -Wl,-no_warn_duplicate_libraries -Wl,-rpath,@executable_path/ -Wl,-rpath,@loader_path/

else ifeq ($(config),debug_linux)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = ../../build/bin
TARGET = $(TARGETDIR)/libgoahead.so
OBJDIR = ../../build/obj/goahead-lib-linux-debug
DEFINES += -DME_VERSION=\"6.1.1\" -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_SSL=1 -DME_COM_OPENSSL_PATH=\"/opt/homebrew\" -DME_COM_MBEDTLS_PATH=\"/usr\" -DME_DEBUG=1
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -fPIC -g -Wall -Wextra -std=gnu11 -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -fPIC -g -Wall -Wextra -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
LIBS += -lrt -ldl -lpthread -lm -lssl -lcrypto
ALL_LDFLAGS += $(LDFLAGS) -L/opt/homebrew/lib -shared -Wl,-soname=libgoahead.so -g -Wl,-z,relro,-z,now -Wl,--as-needed -Wl,--no-copy-dt-needed-entries -Wl,-z,noexecheap -Wl,--no-warn-execstack

else ifeq ($(config),debug_freebsd)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = ../../build/bin
TARGET = $(TARGETDIR)/libgoahead.so
OBJDIR = ../../build/obj/goahead-lib-freebsd-debug
DEFINES += -DME_VERSION=\"6.1.1\" -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_SSL=1 -DME_COM_OPENSSL_PATH=\"/opt/homebrew\" -DME_COM_MBEDTLS_PATH=\"/usr\" -DME_DEBUG=1
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O0 -fPIC -g -Wall -Wextra -std=gnu11 -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O0 -fPIC -g -Wall -Wextra -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
LIBS += -ldl -lpthread -lm -lssl -lcrypto
ALL_LDFLAGS += $(LDFLAGS) -L/opt/homebrew/lib -shared -g

else ifeq ($(config),release_macosx)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = ../../build/bin
TARGET = $(TARGETDIR)/libgoahead.dylib
OBJDIR = ../../build/obj/goahead-lib-macosx-release
DEFINES += -DME_VERSION=\"6.1.1\" -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_SSL=1 -DME_COM_OPENSSL_PATH=\"/opt/homebrew\" -DME_COM_MBEDTLS_PATH=\"/usr\"
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -Wall -Wextra -std=gnu11 -Wno-sign-conversion -Wno-unused-parameter -Wno-unused-result -Wshorten-64-to-32 -Wall -Wno-unknown-warning-option -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -Wall -Wextra -Wno-sign-conversion -Wno-unused-parameter -Wno-unused-result -Wshorten-64-to-32 -Wall -Wno-unknown-warning-option -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
LIBS += -ldl -lpthread -lm -lpam -lssl -lcrypto
ALL_LDFLAGS += $(LDFLAGS) -L/opt/homebrew/lib -dynamiclib -Wl,-install_name,@rpath/libgoahead.dylib -s -Wl,-no_warn_duplicate_libraries -Wl,-rpath,@executable_path/ -Wl,-rpath,@loader_path/

else ifeq ($(config),release_linux)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = ../../build/bin
TARGET = $(TARGETDIR)/libgoahead.so
OBJDIR = ../../build/obj/goahead-lib-linux-release
DEFINES += -DME_VERSION=\"6.1.1\" -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_SSL=1 -DME_COM_OPENSSL_PATH=\"/opt/homebrew\" -DME_COM_MBEDTLS_PATH=\"/usr\"
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -Wall -Wextra -std=gnu11 -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
LIBS += -lrt -ldl -lpthread -lm -lssl -lcrypto
ALL_LDFLAGS += $(LDFLAGS) -L/opt/homebrew/lib -shared -Wl,-soname=libgoahead.so -s -s -Wl,-z,relro,-z,now -Wl,--as-needed -Wl,--no-copy-dt-needed-entries -Wl,-z,noexecheap -Wl,--no-warn-execstack

else ifeq ($(config),release_freebsd)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = ../../build/bin
TARGET = $(TARGETDIR)/libgoahead.so
OBJDIR = ../../build/obj/goahead-lib-freebsd-release
DEFINES += -DME_VERSION=\"6.1.1\" -DME_COM_OPENSSL=1 -DME_COM_MBEDTLS=0 -DME_COM_SSL=1 -DME_COM_OPENSSL_PATH=\"/opt/homebrew\" -DME_COM_MBEDTLS_PATH=\"/usr\"
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -Wall -Wextra -std=gnu11 -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -fPIC -Wall -Wextra -Wno-unused-parameter -Wno-unused-result -Wall -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Wsign-compare
LIBS += -ldl -lpthread -lm -lssl -lcrypto
ALL_LDFLAGS += $(LDFLAGS) -L/opt/homebrew/lib -shared -s -s

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/action.o
GENERATED += $(OBJDIR)/alloc.o
GENERATED += $(OBJDIR)/auth.o
GENERATED += $(OBJDIR)/cgi.o
GENERATED += $(OBJDIR)/crypt.o
GENERATED += $(OBJDIR)/file.o
GENERATED += $(OBJDIR)/fs.o
GENERATED += $(OBJDIR)/http.o
GENERATED += $(OBJDIR)/js.o
GENERATED += $(OBJDIR)/jst.o
GENERATED += $(OBJDIR)/mbedtls.o
GENERATED += $(OBJDIR)/openssl.o
GENERATED += $(OBJDIR)/options.o
GENERATED += $(OBJDIR)/osdep.o
GENERATED += $(OBJDIR)/rom.o
GENERATED += $(OBJDIR)/route.o
GENERATED += $(OBJDIR)/runtime.o
GENERATED += $(OBJDIR)/socket.o
GENERATED += $(OBJDIR)/time.o
GENERATED += $(OBJDIR)/upload.o
OBJECTS += $(OBJDIR)/action.o
OBJECTS += $(OBJDIR)/alloc.o
OBJECTS += $(OBJDIR)/auth.o
OBJECTS += $(OBJDIR)/cgi.o
OBJECTS += $(OBJDIR)/crypt.o
OBJECTS += $(OBJDIR)/file.o
OBJECTS += $(OBJDIR)/fs.o
OBJECTS += $(OBJDIR)/http.o
OBJECTS += $(OBJDIR)/js.o
OBJECTS += $(OBJDIR)/jst.o
OBJECTS += $(OBJDIR)/mbedtls.o
OBJECTS += $(OBJDIR)/openssl.o
OBJECTS += $(OBJDIR)/options.o
OBJECTS += $(OBJDIR)/osdep.o
OBJECTS += $(OBJDIR)/rom.o
OBJECTS += $(OBJDIR)/route.o
OBJECTS += $(OBJDIR)/runtime.o
OBJECTS += $(OBJDIR)/socket.o
OBJECTS += $(OBJDIR)/time.o
OBJECTS += $(OBJDIR)/upload.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo "      [Link] goahead-lib"
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo "     [Clean] goahead-lib"
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) $(foreach f,$(subst /,\\,$(GENERATED)),if exist $(f) del /s /q $(f) >nul &)
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/action.o: ../../src/action.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/alloc.o: ../../src/alloc.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/auth.o: ../../src/auth.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/cgi.o: ../../src/cgi.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/crypt.o: ../../src/crypt.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/file.o: ../../src/file.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/fs.o: ../../src/fs.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/http.o: ../../src/http.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/js.o: ../../src/js.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/jst.o: ../../src/jst.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mbedtls.o: ../../src/mbedtls.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/openssl.o: ../../src/openssl.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/options.o: ../../src/options.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/osdep.o: ../../src/osdep.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/rom.o: ../../src/rom.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/route.o: ../../src/route.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/runtime.o: ../../src/runtime.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/socket.o: ../../src/socket.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/time.o: ../../src/time.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/upload.o: ../../src/upload.c
	@echo "        [CC] $(notdir $<)"
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif